export const types = {
  FETCH_REDDIT: 'FETCH_REDDIT',
  FETCH_REDDIT_SUCCESS: 'FETCH_REDDIT_SUCCESS',
  FETCH_REDDIT_ERROR: 'FETCH_REDDIT_ERROR',
  SORT_REDDIT: 'SORT_REDDIT',
  LOADING: 'LOADING',
};
